format: 'bestaudio/best'
format-sort: [
  'flac'
  ]
audio_channels: 1
postprocessors: [{
  'key': 'FFmpegExtractAudio',
  'preferredcodec': 'flac'
  }]
postprocessor_args: [
  '-ar', '16000',
  '-ac', '1'
  ]
prefer_ffmpeg: True
ffmpeg_location: 'dep/ffmpeg/bin'
outtmpl: './data/audio_files/%(id)s.%(ext)s'